// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-x-5o9eXpeUydXMCeAaCTlbsa2aIQRjg',
    appId: '1:332729957931:android:7d3209b9f441ad486bf46e',
    messagingSenderId: '332729957931',
    projectId: 'solutions-63f02',
    storageBucket: 'solutions-63f02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_dke0i55S04PdNZF13tPKXnDz6gRXDr4',
    appId: '1:332729957931:ios:47525ac7c75a98946bf46e',
    messagingSenderId: '332729957931',
    projectId: 'solutions-63f02',
    storageBucket: 'solutions-63f02.firebasestorage.app',
    androidClientId: '332729957931-h2q50e58vlv9o6vvf0l3vvgu8a3lol3f.apps.googleusercontent.com',
    iosClientId: '332729957931-2nds3mh2u7jf42fb81kt0gqs8f48bgbi.apps.googleusercontent.com',
    iosBundleId: 'com.example.gsccsg',
  );

}